# Generated by Django 4.1.2 on 2023-03-15 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KgmaWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="ФИО преподавателя"),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                ("image", models.ImageField(upload_to="", verbose_name="Фото")),
                ("trailer", models.CharField(max_length=100, verbose_name="Предметы")),
                ("quantity", models.CharField(max_length=100, verbose_name="Контакты")),
                (
                    "speciality",
                    models.CharField(
                        choices=[
                            ('Старший преподаватель', 'Старший преподаватель'),
                            ('Лаборант', 'Лаборант'),
                            ('Лектор', "Лектор"),
                        ],
                        max_length=100,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Commet_TV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Введите ваше имя"),
                ),
                ("text", models.TextField(verbose_name="Ваш коммент")),
                (
                    "rating",
                    models.CharField(
                        choices=[
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                        ],
                        max_length=100,
                        verbose_name="Поставьте оценку",
                    ),
                ),
                (
                    "choise_show",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_object",
                        to="kgmawork.kgmawork",
                    ),
                ),
            ],
        ),
    ]
